# Site settings
title: "Blog | ROSECURE - securitate cibernetica"
description: "ROSECURE este o companie care furnizează servicii și consultanță IT&C, cu  o bogată expertiză în soluții de securitate cibernetică." 
url: "https://blog.rosecure.ro"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
